CI/CD separation

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,50 +1,50 @@
-name: CI - FastAPI Healthcheck
-
-on:
-  push:
-    branches: ["main"]
-  pull_request:
-    branches: ["main"]
-
-jobs:
-  build-test:
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
-
-    - name: Set up Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: '3.11'
-
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install flake8
-        pip install -r requirements.txt
-
-    - name: Lint (flake8)
-      run: |
-        flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
-        flake8 app --count --exit-zero --max-complexity=10 --statistics
-        
-
-    - name: Build Docker image
-      run: |
-        docker build -t healthcheck:ci .
-
-    - name: Run container
-      run: |
-        docker run -d -p 8000:8000 --name healthcheck-test healthcheck:ci
-        sleep 5
-
-    - name: Cleanup
-      if: always()
-      run: |
-        docker stop healthcheck-test || true
-        docker rm healthcheck-test || true
+#name: CI - FastAPI Healthcheck
+#
+#on:
+#  push:
+#    branches: ["main"]
+#  pull_request:
+#    branches: ["main"]
+#
+#jobs:
+#  build-test:
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#    - name: Checkout code
+#      uses: actions/checkout@v4
+#
+#    - name: Set up Python
+#      uses: actions/setup-python@v5
+#      with:
+#        python-version: '3.11'
+#
+#    - name: Install dependencies
+#      run: |
+#        python -m pip install --upgrade pip
+#        pip install flake8
+#        pip install -r requirements.txt
+#
+#    - name: Lint (flake8)
+#      run: |
+#        flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
+#        flake8 app --count --exit-zero --max-complexity=10 --statistics
+#
+#
+#    - name: Build Docker image
+#      run: |
+#        docker build -t healthcheck:ci .
+#
+#    - name: Run container
+#      run: |
+#        docker run -d -p 8000:8000 --name healthcheck-test healthcheck:ci
+#        sleep 5
+#
+#    - name: Cleanup
+#      if: always()
+#      run: |
+#        docker stop healthcheck-test || true
+#        docker rm healthcheck-test || true
 
 #    - name: Deploy to server
 #      uses: appleboy/ssh-action@v1.0.3
@@ -59,3 +59,27 @@ jobs:
 #            --name healthcheck \
 #            -p 8000:8000 \
 #            healthcheck:latest
+name: CD
+
+on:
+  workflow_run:
+    workflows: ["CI"]
+    types:
+      - completed
+
+jobs:
+  deploy:
+    if: ${{ github.event.workflow_run.conclusion == 'success' }}
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout source
+        uses: actions/checkout@v4
+
+      - name: Build image
+        run: docker build -t healthcheck::ci .
+
+      - name: Deploy container
+        run: |
+          docker rm -f healthcheck || true
+          docker run -d -p 8000:8000 --name healthcheck healthcheck::ci
